### ISSUE TITLE
README에서 등장 가능한 펫들의 이미지가 있으면 좋겠습니다.

### ISSUE THREAD

**Issue by falconlee236** [devxb/gitanimals#24]
gitanimals 프로젝트를 잘 이용하고 있습니다.  

제 농장에 나온 동물들이 있는데, 이 동물들이 어떤 확률을 가지는지 현재 텍스트로만 나타나고 있는데,   
해당 동물이 어떻게 생겼는지 확률 옆에 이미지를 추가하면 좋을것 같습니다.

**Comment by devxb** [comment]
빠른 시일내에 추가하도록 하겠습니다 :)
감사합니다.

**Comment by devxb** [comment]
[8a9c988](https://github.com/devxb/gitanimals/commit/8a9c988ec32bbb8d1389a2206a75193f71e9568e)

좀 오래걸렸네요.! 의견 감사합니다 :)
