### ISSUE TITLE
폰트가 명확하지 않은것같습니다. 

### ISSUE THREAD

**Issue by easyhooon** [devxb/gitanimals#47]
사용자에 입장으로서 몇가지 건의 드립니다!

lv(레벨의 약자) 라고 써있는것으로 readme 를 읽으면 이해할 순 있는데, 
w 와 별로 차이가 나지 않아, w7? 이게 뭔 의미이지? 라고 생각이 들 수 있을 것 같습니다. 
폰트가 개발자 감성인것은 맞는데, 가독성이 별로 좋지 않다는 생각이 드네요

그리고 펫이 반대방향으로 이동할때 contribution 이라는 글자가 반대로 뒤집히는데 이럴 경우, 처음 본 사람이 접했을 때, 그 의미를 이해하기 힘든 것 같습니다. 펫이 반대 방향으로 이동할때에도, 글씨는 그대로 유지하여, contribution 이라는 단어를 읽기 용이하도록 하는것이 어떤가 제안을 드려봅니다!

귀여운 거 만들어주셔서 감사합니다!

**Comment by devxb** [comment]
안녕하세요 ")
좋은 의견 감사드립니다. 

lv 폰트의 경우, 아래 처럼 기존의 레거시 폰트에서 새로운 폰트로 수정해 좀 더 명확하게 변경했습니다.

`캐시에 따라서, 릴리즈 후 적용까지 최대 1시간 가량이 소요될 수 있습니다.`

<a href="https://github.com/devxb/gitanimals">
    <img src="https://render.gitanimals.org/lines/devxb?pet-id=17" width="150" height="300"/>
</a>

폰트가 같이 flip되는 이슈는 이전부터 발견되어있던 이슈인데, 해결이 쉽지 않아 보류되고있는 상태입니다. 🥲 (인지는 하고있습니다.)

- #48
